### ISSUE TITLE
No python notebook for chapter 4

### ISSUE THREAD

**Issue by zibuk** [o19s/relevant-search-book#15]

**Comment by JnBrymn-EB** [comment]
This is true! There's really not much code that we would need for that chapter. Rather the examples are meant to be thought experiments for the different ways that you can tokenize your searchable content. If you find any examples that are incorrect, please do let us know. Thanks.

**Comment by softwaredoug** [comment]
there was a branch where I started to do ch 4 examples in an ipynb but
didn't finish. Will try to dig it up (might already. Be on GitHub)

**Comment by softwaredoug** [comment]
Ah yes, it's here. Not 100% complete but has a fair number of the examples

https://github.com/o19s/relevant-search-book/tree/chapter_4
