### ISSUE TITLE
Modify readme including a reference to installing jupyter

### ISSUE THREAD

**Issue by alkampfergit** [o19s/relevant-search-book#16]
Please consider upgrade the readme, 

Running the sample following the readme I got the error: 

`ImportError: No module named notebook.notebookapp`

I needed to 

`pip install jupyter`

to being able to run the sample.

**Comment by LutzenGrutzen** [comment]
Yeah, that would be heavily appreciated. 
Same annoying error here, same simple solution. 
Did cost 15 minutes of my very valuably time.
`pip install jupyter`

**Comment by softwaredoug** [comment]
Updated, thanks!
