### ISSUE TITLE
Missing import statement for requests module

### ISSUE THREAD

**Issue by consulthys** [o19s/relevant-search-book#3]
In the code for chapter 3, I would add an `import requests` statement in the first [boilerplate setup snippet](https://github.com/o19s/relevant-search-book/blob/master/ipython/Chapter%203%20%28Solving%20Your%20First%20Relevance%20Problem%29.ipynb). Otherwise the snippet for indexing data won't run and complain about the missing `requests` module.

**Comment by softwaredoug** [comment]
Fixen in #8 Thanks!
